<?php


namespace app\admin\controller;

use app\admin\model\Config as ConfigModel;
use app\admin\model\ConfigGroup;
use app\admin\service\ConfigWebService;

/**
 * 网站配置
 * @author 牧羊人
 * @date 2020/1/3
 * Class Configweb
 * @package app\admin\controller
 */
class Configweb extends AdminBase
{
    /**
     * 初始化方法
     * @author 牧羊人
     * @date 2020/1/3
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->model = new ConfigModel();
        $this->service = new ConfigWebService();
    }

    /**
     * 系统配置
     * @return mixed
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     * @author 牧羊人
     * @date 2019/5/7
     */
    public function group()
    {
        if (IS_POST) {
            $result = $this->service->group();
            return $result;
        }
        // 配置分组ID
        $group_id = request()->param('group_id', 1);

        // 获取配置分组
        $config_group_model = new ConfigGroup();
        $config_group_list = $config_group_model->where(['mark' => 1])->select();
        $this->assign('config_group_list', $config_group_list);

        // 获取元素列表
        $list = $this->model->getList([['group_id', '=', $group_id]], "id asc");
        if ($list) {
            foreach ($list as &$val) {
                if ($val['type'] == "select") {
                    // 单选下拉
                    $val['format_name'] = "{$val['name']}|1|{$val['title']}|name|id";
                }
                if ($val['type'] == 'checkbox') {
                    // 复选框
                    $val['format_name'] = "{$val['name']}__checkbox|name|id";

                    // 组件数据源
                    $options_list = [];
                    if ($val['options']) {
                        $options = preg_split("/[\r\n]/", $val['options']);
                        if ($options && is_array($options)) {
                            foreach ($options as $v) {
                                $item = explode(':', $v);
                                $options_list[] = [
                                    'id' => $item[0],
                                    'name' => $item[1],
                                ];
                            }
                        }
                    }
                    $val['format_options'] = $options_list;

                    // 选中的值
                    if ($val['value']) {
                        $val['format_value'] = explode(',', $val['value']);
                    }
                }
                if ($val['type'] == 'radio') {
                    // 单选
                    $val['format_name'] = "{$val['name']}|name|id";

                    // 组件数据源
                    $options_list = [];
                    if ($val['options']) {
                        $options = preg_split("/[\r\n]/", $val['options']);
                        if ($options && is_array($options)) {
                            foreach ($options as $v) {
                                $item = explode(':', $v);
                                $options_list[] = [
                                    'id' => $item[0],
                                    'name' => $item[1],
                                ];
                            }
                        }
                    }
                    $val['format_options'] = $options_list;
                }
                if ($val['type'] == 'select') {
                    // 下拉选择
                    $val['format_name'] = "{$val['name']}|1|{$val['title']}|name|id";

                    // 组件数据源
                    $options_list = [];
                    if ($val['options']) {
                        $options = preg_split("/[\r\n]/", $val['options']);
                        if ($options && is_array($options)) {
                            foreach ($options as $v) {
                                $item = explode(':', $v);
                                $options_list[] = [
                                    'id' => $item[0],
                                    'name' => $item[1],
                                ];
                            }
                        }
                    }
                    $val['format_options'] = $options_list;
                }
            }
        }
        $this->assign('list', $list);

        return $this->render('', [
            'group_id' => $group_id,
        ]);
    }
}