<?php

namespace app\admin\widget;

class Tree extends AdminWidget
{
    /**
     * 初始化方法
     * @author zongjl
     * @date 2019/6/19
     */
    public function initialize()
    {
        parent::initialize();
        // TODO: Change the autogenerated stub
    }

    /**
     * 左侧树
     * @return mixed
     * @author zongjl
     * @date 2019/6/19
     */
    public function leftTree($name, $url)
    {
        $this->assign('name', $name);
        $this->assign('url', $url);
        return $this->fetch("widget/tree/left_tree");
    }
}
